#!/usr/bin/env node
/*
 * Copies the Library metrics out of the typed schema into src/metrics.generated.ts.
 *
 *   npm run metrics        (node scripts/gen-metrics.mjs)
 *
 * The typed schema (src/live.metabase.data.ts, from /api/typed-schemas/v1/typescript) carries each
 * metric's description only as a `// Description: …` comment, and the bundle cannot ask Metabase for it
 * at runtime (fetch to the Metabase origin is blocked in the sandbox). The definition cards
 * (src/definitions.ts) need those descriptions so Metabase stays their source of truth, and the
 * instance URL for "Open in Metabase". Run this after every regeneration of the schema.
 *
 * Output: `INSTANCE_URL` and `LIBRARY_METRICS` (id → name, description, source table), sorted by id.
 * It parses the schema's text, so it fails loudly when the generator's layout changes.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const APP = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SCHEMA = join(APP, "src", "live.metabase.data.ts");
const OUT = join(APP, "src", "metrics.generated.ts");

const fail = message => { console.error(`metrics: ${message}`); process.exit(1); };

const text = readFileSync(SCHEMA, "utf8");
const instanceUrl = text.match(/\binstanceUrl:\s*"([^"]+)"/)?.[1];
if (!instanceUrl) fail(`no metabase.instanceUrl in ${relative(APP, SCHEMA)}`);
const generatedAt = text.match(/\bgeneratedAt:\s*"([^"]+)"/)?.[1] ?? "an unknown time";

// The block `const metrics = { … } as const;`: one object per metric at two spaces, its comments above it.
const start = text.search(/^const metrics = \{/m);
if (start < 0) fail("no `const metrics = {` block in the schema");
const end = text.indexOf("\n} as const;", start);
if (end < 0) fail("the metrics block does not end with `} as const;`");

const metrics = [];
let comments = {}, current = null;
for (const line of text.slice(start, end).split("\n").slice(1)) {
  let m;
  if (!current && (m = line.match(/^ {2}\/\/ ([^:]+): (.*)$/))) { comments[m[1].trim()] = m[2].trim(); continue; }
  if (!current && (m = line.match(/^ {2}([A-Za-z_$][\w$]*): \{$/))) {
    current = { key: m[1], description: comments.Description || null, source: comments["Source table"] ?? null };
    comments = {};
    continue;
  }
  if (!current) continue;
  if ((m = line.match(/^ {4}id: (\d+),?$/))) current.id = Number(m[1]);
  else if ((m = line.match(/^ {4}name: ("(?:[^"\\]|\\.)*"),?$/))) current.name = JSON.parse(m[1]);
  else if (/^ {4}type: "metric",?$/.test(line)) current.isMetric = true;
  else if (/^ {2}\},?$/.test(line)) { metrics.push(current); current = null; }
}
if (!metrics.length) fail("found no metrics in the schema");
for (const metric of metrics) {
  if (!metric.isMetric || !Number.isInteger(metric.id) || !metric.name) fail(`could not read metric \`${metric.key}\` (id, name or type is missing)`);
  // "postgres.pumpkin_live.daily_store_sales" → "daily_store_sales"
  metric.table = metric.source?.split(".").pop() ?? "";
}
metrics.sort((a, b) => a.id - b.id);

const rows = metrics.map(mt => `  ${mt.id}: { name: ${JSON.stringify(mt.name)}, description: ${JSON.stringify(mt.description)}, table: ${JSON.stringify(mt.table)} },`);
writeFileSync(OUT, `/*
 * GENERATED by scripts/gen-metrics.mjs from src/live.metabase.data.ts (schema generated ${generatedAt}).
 * Do not edit: regenerate the schema, then run \`npm run metrics\`.
 *
 * The Library metrics with the description Metabase holds for each, for the definition cards
 * (src/definitions.ts). The typed schema keeps descriptions only in comments, so they are copied here.
 */

/** The Metabase instance the schema came from. Definition cards link to \`\${INSTANCE_URL}/metric/<id>\`. */
export const INSTANCE_URL = ${JSON.stringify(instanceUrl.replace(/\/+$/, ""))};

/** Every Library metric in the schema, by card id: its name, its Metabase description (null when it has none) and its source table. */
export const LIBRARY_METRICS: Record<number, { name: string; description: string | null; table: string }> = {
${rows.join("\n")}
};
`);
console.log(`metrics: wrote ${relative(APP, OUT)} (${metrics.length} metrics from ${new URL(instanceUrl).host})`);
