/*
 * GENERATED by scripts/gen-metrics.mjs from src/live.metabase.data.ts (schema generated 2026-10-07T20:57:28.717397691Z).
 * Do not edit: regenerate the schema, then run `npm run metrics`.
 *
 * The Library metrics with the description Metabase holds for each, for the definition cards
 * (src/definitions.ts). The typed schema keeps descriptions only in comments, so they are copied here.
 */

/** The Metabase instance the schema came from. Definition cards link to `${INSTANCE_URL}/metric/<id>`. */
export const INSTANCE_URL = "https://olden-midship.hosted.staging.metabase.com";

/** Every Library metric in the schema, by card id: its name, its Metabase description (null when it has none) and its source table. */
export const LIBRARY_METRICS: Record<number, { name: string; description: string | null; table: string }> = {
  388: { name: "Revenue", description: "Money taken from pumpkins sold, in USD, after markdowns.", table: "daily_store_sales" },
  389: { name: "Pumpkins sold", description: "Pumpkins sold, all channels.", table: "daily_store_sales" },
  390: { name: "Gross margin", description: "Revenue minus the cost of the pumpkins sold, in USD.", table: "daily_store_sales" },
  391: { name: "Gross margin rate", description: "Gross margin as a share of revenue (0–1).", table: "daily_store_sales" },
  392: { name: "Average selling price", description: "Revenue per pumpkin sold, in USD.", table: "daily_store_sales" },
  393: { name: "Revenue plan", description: "The budgeted revenue. For the current day it is paced to the local time, so today compares fairly.", table: "daily_store_sales" },
  394: { name: "Revenue vs plan", description: "Revenue against the plan for the same period: +0.05 = 5% ahead of plan.", table: "daily_store_sales" },
  395: { name: "Last season revenue", description: "Revenue of the 2025 season on the matching days, paced like the plan.", table: "daily_store_sales" },
  396: { name: "Growth vs last season", description: "Revenue against last season for the same days: +0.05 = 5% up.", table: "daily_store_sales" },
  397: { name: "Lost sales", description: "Revenue we could not take because a store ran out of a variety, in USD.", table: "daily_store_sales" },
  398: { name: "Lost sales to late deliveries", description: "Lost sales where the store's van arrived late and the shelf ran empty first.", table: "daily_store_sales" },
  399: { name: "Fill rate", description: "Share of the pumpkins customers asked for that we could sell (0–1).", table: "daily_store_sales" },
  400: { name: "Delivery cost", description: "Cost of the van runs that restocked the stores, in USD.", table: "daily_store_sales" },
  401: { name: "Shrink", description: "Pumpkins damaged in transit or spoiled on the shelf, at cost, in USD.", table: "daily_store_sales" },
  402: { name: "Deliveries", description: "Van runs that reached their store.", table: "deliveries" },
  403: { name: "On-time delivery rate", description: "Share of deliveries that arrived less than 15 minutes after plan (0–1).", table: "deliveries" },
  404: { name: "Bins harvested", description: "Bins of pumpkins picked in the fields.", table: "harvest_daily" },
  405: { name: "Harvest vs plan", description: "Bins picked against the harvest plan (1 = on plan).", table: "harvest_daily" },
  406: { name: "Plan gross margin", description: "The budgeted gross margin: the revenue plan minus the planned pumpkins at this season's unit cost, in USD. For the current day it is paced to the local time, like the revenue plan.", table: "daily_store_sales" },
  407: { name: "Last season gross margin", description: "Gross margin of the 2025 season on the matching days: last season's revenue minus its pumpkins at this season's unit cost, in USD. Paced like the plan.", table: "daily_store_sales" },
  408: { name: "Projected season revenue", description: "Revenue we expect to have taken when the season ends on 15 Nov: revenue so far plus the plan still to come, at the last 7 days' pace against plan, in USD. A projection, not a forecast: the plan already holds the Halloween peak and the November markdowns.", table: "season_landing" },
  409: { name: "Projected leftover after Halloween", description: "Pumpkins we expect to have left on 1 Nov: stock on hand plus the harvest still planned, minus the sales expected to 31 Oct. A variety projected to run short counts as negative. From 1 Nov it is the stock on hand.", table: "stock_outlook" },
  410: { name: "Leftover stock at cost", description: "The pumpkins projected to be left on 1 Nov, valued at what they cost us, in USD.", table: "stock_outlook" },
  411: { name: "Markdown exposure", description: "What the November markdowns are expected to give away on the leftover pumpkins that still sell, in USD.", table: "stock_outlook" },
};
