import type { CountryCode, HarvestStatus, LateInfo, RegionCode, StockStatus, StoreFormat, TruckStatus, Variety } from "../../types";

/*
 * The World tab's contract: the view model the live hook (src/data/useWorldData.ts) builds from fleet_now,
 * hub_now, store_now and cities, and the shape of the map's fixed geometry (./geo.ts, generated by
 * scripts/world/gen_world.py). Everything on the map is placed by the ids the pumpkin_live views use:
 * hub_id ("US-lancaster"), city_key ("US-new-york") and store_id (1..100).
 */

/* ── View model ──────────────────────────────────────────── */

/** fleet_now, one row per van, read for the map. */
export type WorldVan = {
  /** fleet_now.truck_id: "PK-US-107". */
  truckId: string;
  /** fleet_now.fleet_no: 107. */
  fleetNo: number;
  /** fleet_now.truck_label: "Express 107". */
  label: string;
  hubId: string;
  countryCode: CountryCode;
  status: TruckStatus;
  /**
   * The city whose road the van is on: dest_city_key while loading, driving, stopped or unloading; while
   * returning (fleet_now has no destination then) the hub's city whose direction from the hub best matches the
   * van's position. Null at the hub and in the workshop.
   */
  cityKey: string | null;
  /** fleet_now.dest_store_id / dest_store_name: set while loading, driving, stopped and unloading. */
  storeId: number | null;
  storeName: string | null;
  /**
   * How far along the hub → city road the van is, 0 (hub) to 1 (city), when the data arrived: progress_pct / 100
   * on the way out (1 while unloading), the share of the road still ahead of it on the way back. 0 at the hub.
   */
  frac: number;
  /** fleet_now.eta_at (outbound only). */
  etaAt: string | null;
  /** fleet_now.planned_arrive_at (outbound only). */
  plannedAt: string | null;
  /** cities.drive_min of the van's city: how long the road takes, one way (null without a city). */
  driveMin: number | null;
  /** cities.road_km of the van's city. */
  roadKm: number | null;
  /** fleet_now.units_aboard, bins_aboard. */
  units: number;
  bins: number;
  late: LateInfo;
  /** fleet_now.driver_name, make_model, plate. */
  driver: string;
  model: string;
  plate: string | null;
  /** In the workshop: the open fault's description, else "Scheduled service". Null otherwise. */
  workshopJob: string | null;
};

/** store_now, one row per store, read for the map. */
export type WorldShelf = { variety: Variety; onHand: number; capacity: number };
export type WorldStore = {
  storeId: number;
  name: string;
  format: StoreFormat;
  cityKey: string;
  countryCode: CountryCode;
  tz: string;
  stock: StockStatus;
  /** store_now.out_variety (out) or low_variety (low). */
  shortVariety: Variety | null;
  shelves: WorldShelf[];
  isOpen: boolean;
  opensAt: string | null;
  closesAt: string | null;
  /** store_now.next_*: the van on its way, if any. */
  next: { truckId: string; label: string; status: "loading" | "driving" | "stopped" | "unloading"; etaAt: string | null; units: number } | null;
};

/** hub_now, one row per hub. */
export type WorldHub = {
  hubId: string;
  name: string;
  countryCode: CountryCode;
  tz: string;
  harvestStatus: HarvestStatus;
  /** hub_now.harvest_note: "Picking Field 2, 5". */
  harvestNote: string;
  /** The field numbers picking now (from the note), for the field cards. */
  picking: number[];
  binsToday: number;
  planBinsToday: number;
  stockUnits: number;
  stockDays: number;
  vans: { total: number; atHub: number; loading: number; onRoad: number; unloading: number; returning: number; workshop: number; late: number };
};

/** cities, one row per city. */
export type WorldCity = { cityKey: string; name: string; countryCode: CountryCode; hubId: string; roadKm: number; driveMin: number };

/** A line of the Live activity panel: something a van or a store just did. */
export type WorldEventTone = "drive" | "unload" | "back" | "stop" | "out" | "restock";
export type WorldEvent = {
  /** Unique and stable: kind + truck or store + time. */
  key: string;
  /** When it happened (sim clock, ISO). */
  at: string;
  countryCode: CountryCode;
  text: string;
  tone: WorldEventTone;
};

/**
 * The World tab. Every part is undefined while it loads. Not filtered to the scope: the map always shows the
 * whole business and dims what is outside the region; the counters are scoped by the page.
 */
export type WorldViewModel = {
  hubs?: WorldHub[];
  cities?: WorldCity[];
  stores?: WorldStore[];
  vans?: WorldVan[];
  /** Newest last; the page shows the newest few. */
  events?: WorldEvent[];
  /**
   * Client time (Date.now()) when `vans` arrived. With `clock`, it lets the page move vans smoothly between polls.
   * The static preview leaves it out: vans stand where the fixture puts them.
   */
  vansAt?: number;
  /** A part that failed, with nothing to show: its error. */
  errors?: { map?: string };
};

/** The page's own state (seeded by `initial`, e.g. from the static preview's --state). */
export type WorldState = {
  /** The "Show on map" menu is open. */
  layersOpen: boolean;
  /** A counter picked in the strip: only those vans or stores stay bright. */
  focus: WorldStat | null;
  /** The pinned card: "van:PK-US-107", "store:13", "hub:US-lancaster", "workshop:US-lancaster", "field:US-lancaster:2", "city:US-new-york". */
  pinned: string | null;
};

/** The counters above the map. */
export type WorldStat = "driving" | "loading" | "unloading" | "returning" | "hub" | "workshop" | "low" | "out";

/* ── Geometry (./geo.ts) ─────────────────────────────────── */

/** A city plaza's icon: its landmark, or a pumpkin fountain for a city without one. */
export type LandmarkKind = "liberty" | "capitol" | "cntower" | "bigben" | "brandenburg" | "tokyotower" | "libertybell" | "parliament" | "fountain";
export type Pt = [number, number];
/** A box of the plane: its centre and size. */
export type Box = { cx: number; cy: number; w: number; h: number };

/**
 * The map's fixed layout, in plane pixels (the terrain picture's own coordinates). Real coastlines (North America,
 * Britain and Ireland beside the rest of Europe, Japan), magnified around the hubs. A hub is a fenced yard (barn, silo, a lot of 20 bays) inside a ring road; its cities lie in their real
 * direction from it, at a distance that follows the drive time, each road leaving from the ring and ending at the
 * city's plaza, with the city's icon in the middle and its four stores fanned out beyond it on driveways.
 */
export type WorldGeo = {
  /** Plane size. */
  w: number;
  h: number;
  /** The land's bounding box: where the default view looks. */
  fit: { cx: number; cy: number; w: number; h: number };
  /** The minimap: its land path (already scaled), size, and the plane point at its origin. */
  mini: { scale: number; origin: Pt; size: Pt; d: string };
  /**
   * A region's callout points at (x, y); its view fits `fit`, the ground of its hubs, roads, cities and stores; `land`
   * is its land's box, where its dusk and night fall.
   */
  regions: { id: RegionCode; name: string; countries: CountryCode[]; x: number; y: number; fit: Box; land: Box }[];
  /**
   * A hub's yard is centred on (x, y), inside a ring road of radius `ring`. Its barn stands on `barn` (foot), its name
   * on `label`; `bays` are the lot's 20 parking bays (vans park nose up), `workshop` the workshop's foot outside the
   * ring and `workshopBays` the three places in front of it.
   */
  hubs: { hubId: string; countryCode: CountryCode; x: number; y: number; ring: number; barn: Pt; label: Pt; bays: Pt[]; workshop: Pt; workshopBays: Pt[] }[];
  /** A city's road leaves the hub's ring at `from` and ends at the city's plaza (x, y), a quadratic curve through `ctrl`. */
  cities: { cityKey: string; countryCode: CountryCode; hubId: string; x: number; y: number; from: Pt; ctrl: Pt; label: Pt }[];
  /** A store's front door (its sprite stands on it); its driveway runs to the city's plaza. */
  stores: { storeId: number; cityKey: string; x: number; y: number }[];
  fields: { hubId: string; fieldNo: number; variety: Variety; x: number; y: number }[];
  /** Each city's icon, standing in the middle of its plaza (foot at x, y). */
  landmarks: { kind: LandmarkKind; name: string; cityKey: string; x: number; y: number }[];
  decor: { lighthouses: Pt[]; boats: Pt[]; ships: Pt[] };
};
